name: Trigger some action when a pull request is made

on: [pull_request]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"